### ISSUE TITLE
Making SharedContext generic - being able to type initialState

### ISSUE THREAD

**Issue by wucdbm** [frandiox/vite-ssr#103]
Heya, me again.

Have you considered making SharedContext (and anything that extends it as a consequence) generic, in order to be able to select my own type for it like `HookParams<MyStateType>`
What consequences would a change like that introduce to the library in terms of TS errors across entry files?

**Comment by frandiox** [comment]
@wucdbm I think this is possible by doing a type overwrite right now: https://github.com/frandiox/vite-ssr#custom-typings
I think this is more flexible than generics because we would need a bunch of them (initial state, request, respose, and maybe more generics).

Tell me if that works.

**Comment by wucdbm** [comment]
@frandiox Doesn't seem to work for me -- either not at all (it's still Record<string, unknown|any>) or TS keeps complaining that the types are incompatible

Before your suggestion I tried forcing my type by omitting the initialState property and then creating a union with another type that has the correct state type - didn't work either

Something else I could do is actually `const state = initialState as SomeType` and that works well.

Ideally though, I'd like to achieve this: since `import.meta.env.SSR` is always the same value, maybe I could assign two variables, and somehow their type should be dynamic, depending on the SSR boolean - SomeType or never - I was reading an article recently that TS handles these cases in a more sophisticated manner, so if I do `if (import.meta.env.SSR)` in its body one of the vars is never, the other one can be used safely, while in reality, they'd both point to the same object

And dead code elimination should do the rest

**Comment by frandiox** [comment]
@kadiryazici Hey! Can you give some hints here? I guess you need to do something with the `tsconfig.json`?

**Comment by kadiryazici** [comment]
You need to include files to have custom types support.

```json
{
   "compilerOptions": {
   },
   include: [src/**/*]
}
```

### src/types.ts
```ts
export {} // you have to do this otherwise won't work.

declare module 'vite-ssr/vue' {
   export interface Context {
      initialState: {
        someThing: string;
        [key: string]: any;
      }
   }
}
```

**Comment by wucdbm** [comment]
Will give it a try after Wednesday. I've actually used the same approach with another library in main.ts and it seems to be just OK with that one.
