### ISSUE TITLE
How to prerender routes for production?

### ISSUE THREAD

**Issue by kslstn** [frandiox/vite-ssr#105]
The readme says:

> Run `vite-ssr build` for buildling your app. 

I wonder how? The readme doesn't mention installing a CLI.

Context: my production server isn't actually running the application—I want to prerender all routes of my application as html files and put them on basic Apache hosting.

**Comment by frandiox** [comment]
@kslstn Well it mentions you need to install `vite-ssr` as an NPM dependency, which also adds a small CLI to your project.

In any case, Vite SSR is for rendering routes at runtime in your server (server side rendering). It does not support rendering at build time out of the box, and that's what you seem to be looking for.
I would suggest having a look at [`vite-ssg`](https://github.com/antfu/vite-ssg), which has a similar API to vite-ssr.

**Comment by kslstn** [comment]
Thank you! `npx vite-ssr build` is recognized a command (I tried `npm vite-ssr build` before, but that didn't work). Now unfortunately I don't get a build with the sample setup ("Cannot find module 'vite'"), so I'll try vite-ssg.
