### ISSUE TITLE
`dev/server.js` may be replaced by vite plugin hooks?

### ISSUE THREAD

**Issue by yaquawa** [frandiox/vite-ssr#11]
Looking at the `dev/server.js`, I noticed that the motivation to use such a dedicated file is because these two things

1.
https://github.com/frandiox/vite-ssr/blob/f0a7e023cafa767c46d287a99623498381795529/src/dev/server.js#L64

2.
https://github.com/frandiox/vite-ssr/blob/f0a7e023cafa767c46d287a99623498381795529/src/dev/server.js#L85

I think you can utilize these two hooks to get the same result:
https://vitejs.dev/guide/api-plugin.html#config
https://vitejs.dev/guide/api-plugin.html#configureserver

Have I missed anything else? let me know if I'm wrong.

**Comment by frandiox** [comment]
Yes, I think it should be possible to move everything to the plugin (it's in a TODO in the readme that requires some research). It started as a way to support Vite 1, which didn't have a proper plugin API.

One thing to consider is that `vitedge` is wrapping `vite-ssr` so we need to make sure it keeps working.

I guess the new version could run SSR by default and only use SPA (pure Vite) if a `--spa` argument is passed or something like that 🤔 
@yaquawa Would you like to give it a try?

**Comment by yaquawa** [comment]
> I guess the new version could run SSR by default

What did you mean by this? Did you mean there will be a dedicated command just for SSR in the next version of Vite?

**Comment by frandiox** [comment]
Right now, you can run a project using `vite dev`, which is purely SPA mode, or `vite-ssr dev`, which runs in SSR mode.

Since we would be moving the SSR logic from the CLI to the Vite plugin, it will do SSR even when running `vite dev` (instead of SPA), right?

In that case, it would be good to keep the SPA mode in some way. Perhaps `vite dev --spa` could be the command for that. Internally, the plugin would detect this SPA flag and skip all the SSR. Otherwise, defaulting to SPA mode and only doing SSR when `--ssr` is present can work as well.

**Comment by yaquawa** [comment]
Oh, I thought you were saying that the next version of Vite will provide a SSR mode😅
Yes you're right. But this could change the code base a lot, maybe it's a good change to rewrite it to ts🙃

**Comment by frandiox** [comment]
@yaquawa Yeah I'm actually working on that. I'm a bit stuck because we have both ESM and CJS files in the source code, so `tsc` gets confused 😓

**Comment by yaquawa** [comment]
Hi @frandiox 
I just wanna let you know I've created a new plugin that just using the public API of Vite, and that works well.
That could save a lot of maintenance costs, actually the plugin is as tiny as just 100 lines of code.

https://github.com/ssr-glue/vite-plugin

Just for your information, eventually, I went with the server/client entry scripts approach instead of a universal entry script, because Vite won't tree shake the `import.meta.env.SSR` on dev mode, so when you `import` any code that requires node environment, that code will go to client side too, which throw an error that breaks my client code 🤥

**Comment by frandiox** [comment]
@yaquawa Thanks, I'll have a look at it soon, hopefully. That should remove some of the code I had to make to support Vite v1.

>I went with the server/client entry scripts approach instead of a universal entry script, because Vite won't tree shake the import.meta.env.SSR on dev mode, so when you import any code that requires node environment, that code will go to client side too, which throw an error that breaks my client code 🤥

Hah yeah, that's a good reason to use different entry, if your dependencies rely on Node APIs during import. In `vite-ssr` the single entry point is optional, if you want a different entry for the server, you can just provide `--ssr path/to/server/entry` to the CLI.

**Comment by yaquawa** [comment]
@frandiox 
> if you want a different entry for the server, you can just provide --ssr path/to/server/entry to the CLI.

Oh, I didn't notice that before..!  Maybe it should be on the README?

**Comment by frandiox** [comment]
@yaquawa it is, in a "details" section, search for `Using separate entry files` 😅

**Comment by yaquawa** [comment]
Oh really? sorry for that..🤥
