### ISSUE TITLE
Vite publicDir not working since 0.11.x

### ISSUE THREAD

**Issue by jeanfrancoisgb** [frandiox/vite-ssr#116]
Hi,

I just upgraded from 0.10.x, and found that since 0.11.x, Vite publicDir option doesn't seem to work.

On build, I get this error for files in the /public directory, that I did not get on 0.10.x:

> [vite]: Rollup failed to resolve import "/images/logo-white.svg" from "src\layouts\home.vue".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`

The code in home.vue is like this and has not changed:

`<img class="w-auto h-6" src="/images/logo-white.svg" alt="Workflow" />`

It crashes during the "Building SSR bundle for production", the first part works fine.

On 0.10.x, I have a warning on build but it succeeds, can it be related?

> vite v2.6.10 building SSR bundle for production...
> [plugin:replace] @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.

I've also investigated to set the outDir option like in 0.10.x without a success. The content of /public is still properly duplicated in dist/client.

I use your vitesse-ssr starter that I upgraded if that's helpful. I'm lost here.

Any help would be helpful! Thank you!

**Comment by LittleSound** [comment]
I also encountered this problem in the latest vite 2.9.1 and vite-ssr 0.16.0, have you found a solution? @jeanfrancoisgb  @frandiox
