### ISSUE TITLE
Support for React Router 6

### ISSUE THREAD

**Issue by dchenk** [frandiox/vite-ssr#127]
React Router (react-router-dom) version 6 was released in November 2021. The release includes great improvements but also some breaking changes. Are there plans to implement support for v6?

Upgrading docs: https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by frandiox** [comment]
Yeah, I would like to have a look at it now that is released as stable. I also wanted to check the new [React Location](https://react-location.tanstack.com/) but looks like it doesn't support SSR yet 🤔

**Comment by frandiox** [comment]
Implemented (mostly) in #147 and released in `0.16.0` 🎉
