### ISSUE TITLE
Unable to resolve path to module 'vite-ssr'.

### ISSUE THREAD

**Issue by tcastelly** [frandiox/vite-ssr#14]
Hello,

I'm using eslint with:
```js
  extends: ['plugin:react/recommended', 'airbnb'],
```

unfortunately when I try to import 'vite-ssr' I have this error:
> ESLint: Unable to resolve path to module 'vite-ssr'.(import/no-unresolved)

If someone has an idea :)

**Comment by frandiox** [comment]
I'm not sure if it's related but `vite-ssr` is a virtual module, its path doesn't match the actual source code.
It already provides types so I think you can just disable ESLint for that specific import 🤔

**Comment by tcastelly** [comment]
I don't know if it's the best solution, but I updated my `.eslintrc.js` like this:

```js
module.exports = {
 // ...
  settings: {
    'import/core-modules': ['vite-ssr'],
  },
  // ...
}
```

Thank you for your help.
