### ISSUE TITLE
Window not defined in vue/entry-client

### ISSUE THREAD

**Issue by PascalAOMS** [frandiox/vite-ssr#141]
I cloned this repo to try out the Vue example.

Installed all the packages defined in `package.json` and was wondering why it didn't work out of the box.

The first error is this:
![image](https://user-images.githubusercontent.com/17178613/154254503-b52db930-b0db-4502-be46-28b4628c2ac8.png)

So I went into `vue/src/main.ts` and changed `import viteSSR, { ClientOnly } from 'vite-ssr'` to `import viteSSR, { ClientOnly } from 'vite-ssr/vue'`.

Now the server starts but upon visiting localhost:1337 I get this:
![image](https://user-images.githubusercontent.com/17178613/154254729-4077173e-b3bf-4279-addb-f50874a0ebc1.png)

How shall I fix this?

Thank you.

**Comment by frandiox** [comment]
@PascalAOMS Can you downgrade to `vite@2.7.x`? I haven't had the chance yet to check 2.8 and it looks like something is not backwards compatible. I guess you used a package manager differnt from Yarn, right? Otherwise it should have respected `yarn.lock`.

**Comment by PascalAOMS** [comment]
Thank you for the quick response.

Oh wow, it worked with Yarn using the correct lock file.

Appreciate your help.

**Comment by salqueng** [comment]
https://github.com/frandiox/vite-ssr/discussions/143#discussioncomment-2294141
I just made a fix for vite 2.8.x. Can you check it out?

**Comment by Lightnet** [comment]
I got the same error.
`/node_modules/vite-ssr/vue/entry-client.js:24`

`ReferenceError: window is not defined`
