### ISSUE TITLE
Run tests

### ISSUE THREAD

**Issue by riffca** [frandiox/vite-ssr#145]
@frandiox Thank you for great plugin! 
However I can't run tests. Can you give advice how to fix this, please?
![image](https://user-images.githubusercontent.com/16510189/157791383-3ada0646-86cd-46c1-a946-6301bf66cd78.png)

**Comment by frandiox** [comment]
It looks like some of the assertions failed because certain values changed in a third party API. It should be fixed now 👍 

cc @m3hari
