### ISSUE TITLE
Is it possible to add ssr support only to some pages?

### ISSUE THREAD

**Issue by StefanGhiban** [frandiox/vite-ssr#146]
I have been wondering if it is possible to configure the plugin in a way that some pages need ssr and some do not. For example, in an app, you might have a presentation part that needs good seo and other pages after a user logs in that do not need.

**Comment by frandiox** [comment]
You can conditionally pass `skip: true` in your prod server to skip SSR. It will return an empty `index.html` that behaves as SPA:

```js
  const { html, headers } = await renderPage(url, {
    manifest,
    preload: true,
    skip: url.includes('/admin/'),
    request,
    response,
  })
```

**Comment by StefanGhiban** [comment]
Thanks!
