### ISSUE TITLE
[Q]: how to share httponly cookie between ssrContext and ClientContext

### ISSUE THREAD

**Issue by domsen123** [frandiox/vite-ssr#15]
Hi,

how can I pass my httponly cookie from clientcontext to ssrcontext?
My serverside is allways unauthenticated :(

**Comment by frandiox** [comment]
@domsen123 If I'm not understanding wrong, you should find the cookies in the `request` object during SSR. That object can be accessed in the main hook automatically during development:

```js
export default viteSSR(App, { routes }, ({ initialState, request }) => {
   // ...
})
```

In production, you need to pass it to the `render` function in order to be available in the hook:

```js
const { html } = await render(url, {
    manifest,
    preload: true,
    request,
    response,
  })
```

**Comment by domsen123** [comment]
thanks for the fast reply...

ok I'm bit confused right now...

I do auth request (ClientContext): receive cookie Auth={{token}}
If I hit F5 and inspect the request attribute from viteSSR hook, I can see the auth cookie in headers - ok!

I have an simple auth endpoint /checkAuth (checks Auth cookie)

If I hit this request on ClientContext => ok
If I hit this request on ssrContext (api call on setup function and spamming [strg]+ [f5]) = 401

axios withCredentials is set to true... 

My api server is running on :3000...
My vite-ssr is running on :3333...

on api server I set 'access-control-allow-origin': 'http://localhost:3333'

**Comment by frandiox** [comment]
I guess that would be because you need to share the cookies manually between the `request` object you have in SSR (which comes from the browser) and your new API request where you are using fetch or axios.
Since SSR runs in Node, it doesn't know how to attach cookies automatically unlike the browser.

Does that make sense? 🤔

**Comment by domsen123** [comment]
yes... totaly... I am stupid af 😅

now I am creating an axios instance on ssrContext and ClientContext passing the cookie header to the axios instance if available... 

sure - on ssrContext, there is no browser for storing cookies and reuse it "withcredentials".. 

anyways.... thanks for pushing me to the right direction!!! 👍👍👍

**Comment by frandiox** [comment]
No problem, we are all learning here!
