### ISSUE TITLE
How to manually handle SSR page routing under development?

### ISSUE THREAD

**Issue by dreamerblue** [frandiox/vite-ssr#152]
In the "Production" section of the README, it is mentioned that we can control the routing and call `renderPage` to get the SSR result. However, in the "Development" section, the SSR capability can only be used by applying `viteServer.middlewares`, which will cause some custom page routing logic to not be executed in the development environment.

Here is an example which we need to fully control and add some previous logic to page routing, and we hope it can be reused in both Production and Development:

```js
// Handling page '/admin/goods/:id' via Express

// Need to do some pre logic like auth or monitor report
if (!auth(request)) { ... // return 403 }
monitor.reportPageView(url)

// Now execute SSR
if (isProd) {
  const { html, status, statusText, headers } = await renderPage(url, {
    manifest,
    preload: true,
    request,
    response,
  })
} else {
  // how to do it?
}

response.writeHead(status || 200, statusText || headers, headers)
response.end(html)
```

Is there an API (like `renderPage()` in dist/server) to actively trigger SSR for the development environment so that we can manually handle page routing under development?

**Comment by dreamerblue** [comment]
@frandiox  Thanks for your reply. We are using a self developed Node.js framework based on Koa and our current existing page routings include many custom logic. The framework controls routing so that we'd better write logic under it, like the sample below:

```typescript
@get('/admin')
@auth_admin
@some_other_logic
adminPage() {
  // do more custom logic
  return this.render(RenderMode.SSR);
}
```

The control of complex routing logic is necessary for us. And now we are now trying to migrate our project from self handled Webpack SSR to Vite SSR. We like `vite-ssr` because it has a brief API and it focus on SSR itself, no any force integrated file-based routing. So we hope it can provide support for development page routing control like [Vite official SSR demo](https://github.com/vitejs/vite/blob/main/packages/playground/ssr-vue/server.js#L54).

**Comment by frandiox** [comment]
@dreamerblue Alright, after checking this into more details I think it should be possible:

```js
// Create a Vite dev server at the beginning
const viteServer = await createSsrServer({
  server: { middlewareMode: 'ssr' },
})


// ... In the request handling logic:

// Handle your custom routing
if (request.url === '/auth') {
   return 'custom logic'
}


// Use Vite's middlewares property as a request handler and let it handle assets and SSR
const handleRequest = viteServer.middlewares
return handleRequest(request, response)
```

If you don't want Vite to handle assets for you, then you can also try this:

```js
// Create a Vite dev server at the beginning
const viteServer = await createSsrServer({
  server: { middlewareMode: 'ssr' },
})


// ... In the request handling logic:


// Handle your custom routing and assets
if (request.url === '/auth' || request.url.startsWith('/asset') || ...) {
   return 'custom logic'
}

// Load your entry point
const { default: renderPage } = await viteServer.ssrLoadModule('/src/main.js')

// Read the latest versinon of index.html
const template = await readFile(
  path.resolve(viteServer.config.root, 'index.html'),
  'utf-8'
)

// Return manual response using renderPage
const { html, status, statusText, headers } = await renderPage(url, {
  request,
  response,
  template,
})

response.writeHead(status || 200, statusText || headers, headers)
response.end(html)
```


Hope anything from that helps!

**Comment by dreamerblue** [comment]
Thanks! This is helpful for us, and we also refer to some source of vite-ssr dev server. Now it works.
