### ISSUE TITLE
Incompatible with vite-plugin-compress

### ISSUE THREAD

**Issue by Stumblinbear** [frandiox/vite-ssr#16]
When used with `vite-plugin-compress` the resulting files in `./dist` are all compressed.

**Comment by frandiox** [comment]
@Stumblinbear I don't think there's anything that can be done in `vite-ssr` for this.

@aleclarson Do you think it's possible to skip the compression in SSR builds?

**Comment by aleclarson** [comment]
Skip it for both `dist/client` and `dist/server` builds?

**Comment by frandiox** [comment]
@aleclarson I think it's only needed for `dist/server` build. The `dist/client` is only assets that don't need to be imported in Node. Perhaps the only exception is the `dist/client/ssr-manifest.json`, but I guess that can be excluded using the `extentions` option 🤔

**Comment by aleclarson** [comment]
Okay, I've released a fix in v2.1.0

```ts
compress({
  exclude: ['ssr-manifest.json'],
})
```

**Comment by frandiox** [comment]
@aleclarson Thank you for the quick update!

@Stumblinbear please try the new version of `vite-plugin-compress` with the new `exclude` option as mentioned 👍
