### ISSUE TITLE
[Question] How can I bundle all dependencies in server build? 

### ISSUE THREAD

**Issue by domsen123** [frandiox/vite-ssr#161]
Is it possible to bundle (or specific) dependencies in server build? I tried with some rollup plugins "commonjs, resolve" etc. but nothing works :(

**Comment by frandiox** [comment]
Try with [`ssr.noExternal: true`](https://vitejs.dev/config/#ssr-noexternal). It will fail if you are importing Node built-ins, though.

**Comment by domsen123** [comment]
thanks - this works....
