### ISSUE TITLE
Inital state does not serialize getters, setters and functions of the object

### ISSUE THREAD

**Issue by yuriifabirovskyi** [frandiox/vite-ssr#164]

**Comment by frandiox** [comment]
Serialization can be customized: https://github.com/frandiox/vite-ssr#state-serialization
You can use libs like [`serialize-javascript`](https://www.npmjs.com/package/serialize-javascript) for what you're asking.

**Comment by yuriifabirovskyi** [comment]
@frandiox Wow! That is very usefull. Thanks!
