### ISSUE TITLE
Vite 3.0.0 and 3.1.0 support

### ISSUE THREAD

**Issue by yuriifabirovskyi** [frandiox/vite-ssr#178]
I noticed 2 problems. Maybe there is more.
1. Starting with vite 3.0.0, the server entry point is built as main.mjs instead of main.js, as it was before.
2. Assets folder is building in server mode in v3.1.0.
![image](https://user-images.githubusercontent.com/20482699/189080722-cbb32275-1f6c-441d-9af9-b904180c12f4.png)

**Comment by gitsheny** [comment]
vite文档上有
vite.config.js
`ssr: {
      format: 'cjs',
    },`
