### ISSUE TITLE
Vite 3.x.x support

### ISSUE THREAD

**Issue by Lord-Y** [frandiox/vite-ssr#182]
@frandiox Any plan to support Vite 3.x.x?

**Comment by bitem-cn** [comment]
I already use this in vite3

**Comment by frandiox** [comment]
Yeah I know some other projects using Vite 3 with Vitedge, which uses vite-ssr internally. Did you find any issue using this in Vite 3 apart from some versioning warnings?

**Comment by bitem-cn** [comment]
> Yeah I know some other projects using Vite 3 with Vitedge, which uses vite-ssr internally. Did you find any issue using this in Vite 3 apart from some versioning warnings?

Just a few deployment issues, which I've taken care of.

**Comment by Lord-Y** [comment]
@frandiox I stood with version 0.16.0 as I intent to use it soon in production.

**Comment by frandiox** [comment]
0.17.0 supports Vite 4 now so I'm closing this 👍
