### ISSUE TITLE
Way to pass router configuration [VUE]

### ISSUE THREAD

**Issue by jwahdatehagh** [frandiox/vite-ssr#27]
Hi - great package!

What do you think about adding the possibility to pass router configuration to the viteSSR? Right now it's not possible to leverage other configuration options like `scrollBehavior` or `linkActiveClass`.

Happy to work sth out and submit a PR as well.

**Comment by frandiox** [comment]
@jwahdatehagh  Hi! Sure, a PR would be welcome.
Maybe an API like this?

```ts
import type { RouterOptions } from 'vue-router'

viteSSR(App, {
  routes: [],
  routerOptions: Omit<RouterOptions, 'routes' | 'history'>
}, () => { ... })
```

**Comment by lautiamkok** [comment]
@frandiox 

It doesn't work. Getting this error:

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vue-router.js?v=e55863d5' does not provide an export named 'RouterOptions'`

**Comment by frandiox** [comment]
`RouterOptions` is just a type. You can pass options (`scrollBehavior`, etc) like in [this example](https://github.com/frandiox/vite-ssr/discussions/160#discussioncomment-2718997).

**Comment by lautiamkok** [comment]
@frandiox got it working now. thanks so much!
