### ISSUE TITLE
Internal server error: Unexpected token '.'

### ISSUE THREAD

**Issue by nwaughachukwuma** [frandiox/vite-ssr#28]
Hi @frandiox, thanks for such an awesome library.

I'm currently getting the following error when I try to declare and use Vuex store

```sh
[vite] Error when evaluating SSR module /src/store/store.getters.ts:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/Users/xxx/.../node_modules/.pnpm/vite@2.3.4/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:68222:9)
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/Users/xxx/.../node_modules/.pnpm/vite@2.3.4/node_modules/vite/dist/node/chunks/dep-6b5f3ba8.js:68222:9)
3:38:59 PM [vite] Internal server error: Unexpected token '.'
```

> store.getters.ts

```ts
import { GetterTree } from 'vuex'
import { StoreState } from './store.state'

const getters: GetterTree<StoreState, StoreState> = {
  isAuthenticated(state) {
    return !!state.user?.uid
  }
}

export default getters
```

If I removed the optional chaining `state.user?.uid` and did `state.user && state.user.uid` it works alright. This has caused me to dynamically import `createStore` and initialize the store when not in SSR mode

```ts
const unwrapStore = () => import('./store/store.index')

export default viteSSR(
  App,
  { routes, base: () => '/' },
  async ({ app, router, initialState, initialRoute }) => {
  
   if (!import.meta.env.SSR) {
      const r = await unwrapStore()
 	  const store = r.default()
      app.use(store, r.key)
      store.replaceState(initialState)
    }
})
```
Now the problem is that I can't use the store in `setup()` in SSR mode. So the following will either fail or throw an error `cannot reference commit of undefined`

```ts
setup() {
  const store = useStore()

  store.commit("ACTION", payload)
}

```

**Comment by nwaughachukwuma** [comment]
@frandiox, this looks like it's related to Vite. Any thought on what fixing it would require?

**Comment by frandiox** [comment]
@nwaughachukwuma Didn't have time to check this properly but the syntax issue might be related to `tsconfig.json` if you are on TypeScript (lower the target/lib to `es2019` or whatever). Otherwise, try latest Node 14 and see if that works.

**Comment by nwaughachukwuma** [comment]
> Otherwise, try the latest Node 14 and see if that works.

This fixed it, thank you!
