### ISSUE TITLE
Route params not exposed as props in SPA mode

### ISSUE THREAD

**Issue by nwaughachukwuma** [frandiox/vite-ssr#29]
Say I define my routes as follows:

```ts
export const routes = [
  {
    path: '/',
    component: () => import('./pages/Home.vue'),
    name: Routes.Home,
  },
  {
    name: 'UserProfile',
    path: '/user/:uid',
    component: () => import('./pages/User.vue'),
    props: true,
  },
  {
    path: '/:catchAll(.*)',
    name: 'not-found',
    component: () => import('./pages/404.vue'),
  }
]
```
...In SPA mode, I don't get the `vid` param as a prop and in SSR mode, I have to patch `to.meta.state` as shown below to get `vid` param injected into the component as a prop.

```ts
router.beforeEach((to, from, next) => {
   if (to.meta.state) {
       return next()
   }
   // pass route params to the page as props
   to.meta.state = Object.assign(
    {},
    to.meta.state,
    initialState,
    initialRoute.params,
   )
  next()
})
```

I guess I'm not doing something right

**Comment by frandiox** [comment]
@nwaughachukwuma Thanks for reporting! Can you try `0.10.2` and [add `props: true` to your routes](https://next.router.vuejs.org/guide/essentials/passing-props.html#passing-props-to-route-components)?

**Comment by nwaughachukwuma** [comment]
Thank you @frandiox, it works alright now!
