### ISSUE TITLE
/public manifest.json overwritten

### ISSUE THREAD

**Issue by stolinski** [frandiox/vite-ssr#31]
Using the latest, if you have a public/manifest.json for Web app manifests https://developer.mozilla.org/en-US/docs/Web/Manifest it becomes overridden to nothing. 

I've found a work around by putting the manifest file in a folder. I can add a note to the readme about this if this functionality is intended.

**Comment by frandiox** [comment]
@stolinski Vite was creating the manifest automatically and overwriting yours. In the latest version it will be only generated if you pass `build.manifest: true` in your `vite.config.js` 👍
