### ISSUE TITLE
[SSR] On state serialization - TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by daichi-ranguru** [frandiox/vite-ssr#35]
Hey comunity!

I found myself in weird position where I found something that may be a bug(?) - namely: When this plugin tries to stringify state (in utils/state.js) that is then injected to FE, the JSON.stringify throws and error that theres circular structure.

It throws error like this:
<pre>`[SSR] On state serialization - TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'something' -> object with constructor 'Object'
    |     property 'something' -> object with constructor 'Object'
    |     ...
    |     property 'something' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
    at serializeState (/node_modules/vite-ssr/utils/state.js:32:36)
    at eval (/node_modules/vite-ssr/vue/entry-server.js:64:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async handleSsrRequest (C:\Users\Workgroup-L\Desktop\Work\radixal\mortage\mortgage\FE\node_modules\vite-ssr\dev\server.js:88:31)`</pre>

Should it use flatted package or have something like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value)?

Open to make a PR myself! Thanks.

**Comment by frandiox** [comment]
@daichi-ranguru Hi! The default serialization strategy assumes you have an object that can be passed to `JSON.stringify`. Circular dependencies break `JSON.stringify` so you need to either fix that on your end (removing circular deps in your `initialState` object), or overwrite the default serialization strategy.

To overwrite it, there's a hook mentioned [here](https://github.com/frandiox/vite-ssr#state-serialization) where you can use something like [devalue](https://github.com/Rich-Harris/devalue).
Hope that helps!

**Comment by daichi-ranguru** [comment]
@frandiox  Hey! Glad to hear from you this quickly - writing my custom hook helped! 
Ill leave this here for future if someone gets this error too, but somehow didnt figure it out from docs.

Thanks again!
