### ISSUE TITLE
Upgrade to Vite 2

### ISSUE THREAD

**Issue by benmccann** [frandiox/vite-ssr#4]
I see that this project uses `^1.0.0-rc.9`

https://github.com/frandiox/vite-ssr/blob/33fa848eaaa68026683628cb5df9e5a06ecea2f2/core/package.json#L25

I'd really love to see it use the latest - `2.0.0-beta.33`

**Comment by frandiox** [comment]
@benmccann Version `0.1.0` supports Vite 2 👍

**Comment by benmccann** [comment]
Wow, thanks!
