### ISSUE TITLE
inject req and res to context so it's accessible via `useSsrContext`

### ISSUE THREAD

**Issue by ekoeryanto** [frandiox/vite-ssr#5]
It's kinda feature request

**Comment by frandiox** [comment]
@ekoeryanto Released in `0.1.2`!

What's your use case for this? I've added `initialState` to the SSR context as well so it can be mutated. The resulting state will be hydrated later in the client. I think this could be an alternative to using `router.meta.state` 🤔

**Comment by ekoeryanto** [comment]
`req` to check the session, cookie, etc. and the `res` to redirect,
