### ISSUE TITLE
bootsrap

### ISSUE THREAD

**Issue by domsen123** [frandiox/vite-ssr#52]
how can I load bootrap 5 in client only?

**Comment by frandiox** [comment]
I don't know much about bootstrap but there are a few ways to load things only in browser:

- `if (!import.meta.env.SSR) { await import('...') }`
- `if (!import.meta.env.SSR) { document.body.appendChild(document.createElement('script')) }`
- Use two separate entry points (see "Using separate entry files" in [Readme#Usage](https://github.com/frandiox/vite-ssr#usage)).

If you want to render part of your app only in client, use [`ClientOnly` component](https://github.com/frandiox/vite-ssr#rendering-only-in-clientbrowser).

Hope that helps!
