### ISSUE TITLE
Base path

### ISSUE THREAD

**Issue by michalpaukert** [frandiox/vite-ssr#67]
Hi,
is there possibility to use this configuration https://vitejs.dev/config/#base to configure base path?

In my case it is not working if I use this in vite.config.ts with this configuration: "build": "node node_modules/vite-ssr/cli.js build",

**Comment by frandiox** [comment]
@michalpaukert Did you figure it out?

**Comment by michalpaukert** [comment]
Yes it is configurable in vite.config, but does not work in development mode
