### ISSUE TITLE
Multiple entry points

### ISSUE THREAD

**Issue by danelowe** [frandiox/vite-ssr#7]
I'd like to be able to build a separate mobile and desktop app with some shared code, and the same npm dependencies, but different builds. I would expect that most people would want to set up projects in this way, but always find it difficult to do for some reason. 

From what I can see, it looks like `vite-ssr` could make this easier by:

1. Either allowing configurable entrypoint for both client and server (mobile.html/desktop.html vs index.html), or allowing for dynamically resolving the `App` that is passed to `viteSSR()`
2. Allowing for configurable `outDir`

At this stage I'm not really sure how feasible this would be, so i might just rewrite or move a file in my `package.json` scripts until things become easier.

**Comment by frandiox** [comment]
@danelowe Hello! Would the [multi-page-app](https://vitejs.dev/guide/build.html#multi-page-app) approach in Vite work for you in development? I just need to figure out if that API is good enough so we can add support in `vite-ssr` build. I haven't played with this kind of build so not sure what's needed. If you want to experiment with that I'd be happy to review ideas.

> 1. Either allowing configurable entrypoint for both client and server (mobile.html/desktop.html vs index.html), or allowing for dynamically resolving the App that is passed to viteSSR()

I think you can probably do this yourself by using `alias`, e.g. `alias: { 'my-dynamic-app': process.env.BUILD_MOBILE ? 'src/mobile-app.vue' : 'src/desktop-app.vue' }` in the `vite.config.js`. Then, you just `import App from 'my-dynamic-app'` in `main.js`. This should work for both dev and build 🤔 

> 2. Allowing for configurable outDir

There are 2 builds in vite-ssr, one for the client and one for the server. Therefore, a CLI flag `--outDir` would be ambiguous. Maybe we should add `--client-outDir` and `--server-outDir` or something like that 🤔 
In the meantime, you can use the JS API of `vite-ssr`:

```js
const ssrBuild = require('vite-ssr/build')

await ssrBuild({ clientOptions: {...}, serverOptions: {...} })
```

There should be typings there, but just in case you can check this [file](https://github.com/frandiox/vite-ssr/blob/master/src/build.js).

**Comment by danelowe** [comment]
Hi @frandiox, 

Sorry for the delayed reply. I didn't get a notification for some reason.

I ended up starting with the example from the vite repo rather than `vite-ssr`, because I later realised that I needed more control over the whole process and had to set up a custom server.

I've pulled out an earlier version of this and published to https://github.com/danelowe/vue-ssr-template so you can see what I ended up doing. It mostly came down to dynamic values in the vite config.

The alias is a great idea. It's simplified things quite a bit. I had already been using a dynamic alias for getting pages from different directories, but hadn't considered I could load the main app that way!

**Comment by danelowe** [comment]
@frandiox The example was simplified to illustrate the multi-device thing more, and I'd removed a lot of custom stuff. 

I can't recall the specific details, but I believe the issue I was something to do with injecting a websocket client into the app with values taken from the request headers. I understand `vite-ssr` provides access to the request now, but there was something in my specific case that was complicating things. Actually, I think it might have been that I wanted to load `w3cwebsocket` in SSR, but not have it in the client bundle. There are a few other cases like this, and because I'm migrating a Nuxt app, I did what I could to keep the majority of the existing code similar. Sorry for the lack of detail.
