### ISSUE TITLE
Exports and export assignments are not permitted in module augmentations

### ISSUE THREAD

**Issue by wucdbm** [frandiox/vite-ssr#83]
Hi and thanks for what looks to be a very promising library

`node_modules/vite-ssr/index.d.ts:21:3 - error TS2666: Exports and export assignments are not permitted in module augmentations.`

Got this while linting the project with `vue-tsc --noEmit`

```
// This is a generic mix of framework types
import type { SharedContext, SharedOptions } from './utils/types'

declare module 'vite-ssr' {
  const handler: (
    App: any,
    options: SharedOptions & {
      routes: Array<Record<string, any>>
      routerOptions?: Record<string, any>
      styleCollector?: (ctx: any) => any
    },
    hook?: (
      params: SharedContext & {
        app: any
        router: any
        initialRoute: any
      }
    ) => any
  ) => any

  **export** default handler
  export const ClientOnly: any
  export const useContext: () => SharedContext
}
```

Updated `export default handler` to 

```
  export default function (
      App: any,
      options: SharedOptions & {
          routes: Array<Record<string, any>>
          routerOptions?: Record<string, any>
          styleCollector?: (ctx: any) => any
      },
      hook?: (
          params: SharedContext & {
              app: any
              router: any
              initialRoute: any
          }
      ) => any
  ): any
```

And it stopped complaining.
Unfortunately, my skills in JS/TS only allow me to do so much -- I am completely clueless how to fix that so that the built version of the library on NPM will generate the proper `.d.ts` file

Anyone any ideas?

**Comment by wucdbm** [comment]
For anyone else wondering about, I found out that setting `"skipLibCheck": true,` under `compilerOptions` in tsconfig.json fixes the problem

I am unsure whether anything should be done with the library itself

Leaving it open for other strangers wondering what's going on

**Comment by frandiox** [comment]
Thanks for posting your solution! I'll check if this can be changed without breaking anything.
