### ISSUE TITLE
Custom Context Types

### ISSUE THREAD

**Issue by kadiryazici** [frandiox/vite-ssr#87]
Hi, I'm trying to add custom types to context but none of things I tried worked. Is there a way for this?

```ts
import {Request, Response} from 'express';

declare module 'vite-ssr' {
   export interface Context {
      request: Request,
      response: Response
   }
}
```

or

```ts
import {Request, Response} from 'express';

declare module 'vite-ssr/vue' {
   export interface Context {
      request: Request,
      response: Response
   }
}
```

**Comment by frandiox** [comment]
I'm not an expert in TS types honestly, so not sure how it can be overridden. One thing you could do if you are using `useContext`, is create your own wrapper and export it: `export const myUseContext = () => useContext() as MyContext`

**Comment by kadiryazici** [comment]
Maybe it is because you used `type` instead of `interface`. I will try to make a pull request.

**Comment by frandiox** [comment]
Closed in https://github.com/frandiox/vite-ssr/pull/89
