### ISSUE TITLE
Custom index.html

### ISSUE THREAD

**Issue by KaelWD** [frandiox/vite-ssr#88]
I have a testing environment that can use either vite or webpack, and to do this I've create a separate `index.vite.html` and `index.webpack.html` for each bundler. The following plugin works for vite without SSR, but vite-ssr has `index.html` hardcoded. I can't actually have a file called `index.html` or webpack will try to serve it. 

```js
{
  name: 'configure-server',
  configureServer(server) {
    return () => {
      server.middlewares.use('/', (req, res, next) => {
        if (req.url === '/index.html') req.url = '/index.vite.html'
        return next()
      })
    }
  }
},
```

https://github.com/frandiox/vite-ssr/blob/2019dc695a395175b05228f0943528456efdf8db/src/dev/server.ts#L52-L56

**Comment by frandiox** [comment]
Hmm, yep, in SSR we need to read the original index.html template to inject stuff for every request, even those that are not directed to "index.html".

It doesn't look like Vite has an official way to modify `index.html` name in development but it has for production (using rollupOptions.input). Perhaps we can adopt that same API for development as well, so you just need to provide `rollupOptions: { input: '...../index.vite.html' }` in `vite.config.js`. Would that work for you?

**Comment by frandiox** [comment]
@KaelWD At the end it will be an option of vite-ssr plugin because the one I mentioned earlier conflicts with the SSR build. `viteSSR({ input: path.resolve(__dirname, 'index.vite.html') })`. Will be released soon.
